### ISSUE TITLE
About Login

### ISSUE THREAD

**Issue by CHN-Coding** [alaahong/open_test_class#1]
登录这一块可不可以用redis + token 方式实现？ @alaahong

**Comment by alaahong** [comment]
可以啊。不过假如你是根据JSR-107做实现的话，换一个单机的实现会更方便检查效果。（这也是为啥选数据库要求H2的原因）

**Comment by wangzhe-007** [comment]
这个是我做的,但是时间有限,是说一天之内必须完成吗?我没有搞完,就剩下繁琐的前端和一些简单的curd的操作了,因为今天去面试了,今天下午搞了一下午,时间太紧,好多都没做,主要是我拿到的有offer了怕错过您这边的面试,今天晚上匆忙提交了一个版本.....前台很low,,,,数据库没有用过H2,,,所以弄了假数据,https://github.com/wangzhe-007/zhadaDemo.git

**Comment by alaahong** [comment]
> 这个是我做的,但是时间有限,是说一天之内必须完成吗?我没有搞完,就剩下繁琐的前端和一些简单的curd的操作了,因为今天去面试了,今天下午搞了一下午,时间太紧,好多都没做,主要是我拿到的有offer了怕错过您这边的面试,今天晚上匆忙提交了一个版本.....前台很low,,,,数据库没有用过H2,,,所以弄了假数据,https://github.com/wangzhe-007/zhadaDemo.git

您是哪一位？手头没有收到过跟ID类似的简历。

**Comment by wangzhe-007** [comment]
您好我是王斌彪,我昨天做的,

**Comment by alaahong** [comment]
> 王斌彪

您好，没有任何人推送过您的简历给我们。
我们这边并没有您的记录。请问是谁联系的您？
