### ISSUE TITLE
submit task 

### ISSUE THREAD

**Issue by itstars** [alaahong/open_test_class#2]
您好，
我是文思海辉公司的面试人员，已按需求简单完成了此项目，烦请查阅。
git地址：https://github.com/itstars/open_test_class_zhangheng.git
## 初始化数据说明：
用户管理初始化4个用户账号，分别为admin、teacher、stu1和stu2；密码都是123。
admin具有用户操作权限,可以对用户管理菜单进行操作；
teacher具有教师权限，可对课程管理菜单进行操作；
stu1和stu2具有学生权限，可对订阅管理菜单进行操作。
课程管理初始化了语文、数学、英语三门课程，均为有效状态。

**Comment by alaahong** [comment]
Hi just comment with your commit. Thanks.
