### ISSUE TITLE
bug fix

### ISSUE THREAD

**Issue by aguai0** [alaahong/open_test_class#4]

**Comment by alaahong** [comment]
Thanks for your updated, but it's still not friendly. You didn't think about review part, we have to concern the cooperation in daily work.

1. Still not provide test data, we have to manual check your logic and insert data even including account by self?
![image](https://user-images.githubusercontent.com/3264250/89480700-95825880-d7c8-11ea-8e31-326c3038c6da.png)
2. Had you tested your functions? How can you provide such functions to user? Who can login your system?
![image](https://user-images.githubusercontent.com/3264250/89480911-25280700-d7c9-11ea-9104-f16aa49d16f4.png)
![image](https://user-images.githubusercontent.com/3264250/89480938-3709aa00-d7c9-11ea-949b-b15c2bb11eda.png)
